## Wifi
CIRCUITPY_WIFI_SSID = "BOUGEIT"
CIRCUITPY_WIFI_PASSWORD = "Cpiercey1!"

## Data collection constants
# Choose a unique device ID for your device, e.g. "yourname-co2-temperature"
DEVICE_TIMEZONE = "America/Tijuana" # http://worldtimeapi.org/timezones
DEVICE_ID = "Chuck_Piercey_Battery_Sensor"

# To enable modifying files from the web. Change this too!
# Leave the User field blank when you type the password into the browser.
CIRCUITPY_WEB_API_PASSWORD="festival"

CIRCUITPY_WEB_API_PORT=80

# Public/anonymous connection info for our supabase instance
# (Yep, we've just put the access key in plaintext here :o )
SUPABASE_POST_URL = "https://zuwvqaycrihgxufuzmhu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1d3ZxYXljcmloZ3h1ZnV6bWh1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwNzA3Nzc0NCwiZXhwIjoyMDIyNjUzNzQ0fQ.FQIoaoTCuoUuDvgWBhCkAqv8g5S06mBxCVLm-Xw6aKs"